<?php

declare(strict_types=1);

namespace IdSign\ImageBundle\DependencyInjection;

use Symfony\Component\Config\Definition\Builder\TreeBuilder;
use Symfony\Component\Config\Definition\ConfigurationInterface;

class Configuration implements ConfigurationInterface
{
    public function getConfigTreeBuilder(): TreeBuilder
    {
        $treeBuilder = new TreeBuilder('id_sign_image');

        $treeBuilder->getRootNode()
            ->children()
                ->arrayNode('device_sizes')
                    ->integerPrototype()->end()
                    ->defaultValue([640, 750, 828, 1080, 1200, 1920, 2048, 3840])
                ->end()
                ->integerNode('default_quality')
                    ->defaultValue(80)
                ->end()
                ->arrayNode('formats')
                    ->scalarPrototype()->end()
                    ->defaultValue(['avif', 'webp'])
                ->end()
                ->arrayNode('cache')
                    ->addDefaultsIfNotSet()
                    ->children()
                        ->integerNode('ttl')
                            ->defaultValue(2592000)
                        ->end()
                        ->scalarNode('path')
                            ->defaultValue('%kernel.project_dir%/public/_image')
                        ->end()
                    ->end()
                ->end()
                ->arrayNode('blur')
                    ->addDefaultsIfNotSet()
                    ->children()
                        ->booleanNode('enabled')
                            ->defaultFalse()
                        ->end()
                        ->integerNode('size')
                            ->defaultValue(10)
                        ->end()
                        ->integerNode('quality')
                            ->defaultValue(30)
                        ->end()
                    ->end()
                ->end()
                ->scalarNode('default_watermark')
                    ->defaultNull()
                    ->info('Default watermark profile name applied to all images (null = no watermark)')
                ->end()
                ->arrayNode('watermarks')
                    ->useAttributeAsKey('name')
                    ->arrayPrototype()
                        ->children()
                            ->scalarNode('path')
                                ->isRequired()
                            ->end()
                            ->enumNode('position')
                                ->values(['top-left', 'top-center', 'top-right', 'center-left', 'center', 'center-right', 'bottom-left', 'bottom-center', 'bottom-right'])
                                ->defaultValue('bottom-right')
                            ->end()
                            ->integerNode('opacity')
                                ->defaultValue(50)
                                ->min(0)->max(100)
                            ->end()
                            ->integerNode('size')
                                ->defaultValue(20)
                                ->info('Watermark width as percentage of output image width')
                            ->end()
                            ->integerNode('margin')
                                ->defaultValue(10)
                                ->info('Margin from edge in pixels')
                            ->end()
                        ->end()
                    ->end()
                ->end()
                ->booleanNode('auto_dimensions')
                    ->defaultFalse()
                ->end()
                ->booleanNode('lossless')
                    ->defaultFalse()
                    ->info('Global default for lossless encoding. Applies to WebP and AVIF outputs; silently ignored for JPEG (no lossless mode) and PNG (already lossless). AVIF lossless requires libheif with AV1 encoder plugin (libheif-plugin-aomenc on Debian/Ubuntu).')
                ->end()
                ->integerNode('max_width')
                    ->defaultValue(4096)
                    ->min(1)
                    ->info('Maximum accepted output width in pixels. Protects against memory exhaustion from accidentally large values.')
                ->end()
                ->integerNode('max_source_bytes')
                    ->defaultValue(20_971_520) // 20 MiB
                    ->min(0)
                    ->info('Maximum source file size in bytes. Protects against decompression bombs and large accidental uploads. 0 disables the check.')
                ->end()
                ->variableNode('file_permissions')
                    ->defaultValue(0o660)
                    ->validate()
                        ->ifTrue(static fn ($v): bool => null !== $v && !\is_int($v))
                        ->thenInvalid('file_permissions must be an integer (e.g. 0o660) or null.')
                    ->end()
                    ->info('Permissions for created cache files (e.g. 0660). Null = use umask default.')
                ->end()
                ->integerNode('directory_permissions')
                    ->defaultValue(0o770)
                    ->info('Permissions for created cache directories (e.g. 0770).')
                ->end()
                ->enumNode('serve_mode')
                    ->values(['controller', 'public'])
                    ->defaultValue('public')
                ->end()
                ->scalarNode('route_prefix')
                    ->defaultValue('/_image')
                ->end()
            ->end()
        ;

        return $treeBuilder;
    }
}
